
name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  IMAGE_NAME: suntsovvv/web-app-diploma
  NAMESPACE: default
  DEPLOYMENT_NAME: web-app-diploma

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Docker tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          web-app=${{ env.IMAGE_NAME }}:${{ env.TAG }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}          
 #     - name: Build Docker image
#        run: |
 #         docker build . -t suntsovvv/web-app-diploma:${{ env.tag }}
      

          
  #    - name: Push Docker image
   #     run: |
    #      docker push suntsovvv/web-app-diploma:${{ env.tag }}
    
  #    - name: Deploy to Kubernetes
   #     run: |
    #      kubectl set image deployment/web-app-diploma web-app-diploma=suntsovvv/web-app-diploma:${{ env.tag }} -n web-app-diploma
     #     kubectl rollout status deployment/web-app-diploma -n web-app-diploma
