
name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build . -t suntsovvv/web-app-diploma:${{ env.tag }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push Docker image
        run: |
          docker push suntsovvv/web-app-diploma:${{ env.tag }}

#      - name: Set up Kubernetes context
 #       run: |
  #        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
   #       export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/web-app-diploma web-app-diploma=suntsovvv/web-app-diploma:${{ env.tag }} -n web-app-diploma
          kubectl rollout status deployment/web-app-diploma -n web-app-diploma
